#!/bin/bash
export ROS_MASTER_URI=http://ubiquityrobot.local:11311
echo Connecting to $ROS_MASTER_URI

if [ -z "$1" ]; then
    rosrun map_server map_saver;
else
    rosrun map_server map_saver -f $1;
fi
