#!/bin/bash
git push robot master
catkin_make install
source devel/setup.bash
ssh ubuntu@ubiquityrobot.local "cd /home/ubuntu/BallCollectorProject && ./startup-core" &
roslaunch launch/hector.launch &
rosrun rviz rviz &
rosrun rqt_console rqt_console &
rosrun cortex_driver drive_console &
